/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'textiles' : null } |
  { 'furniture' : null } |
  { 'lighting' : null } |
  { 'decor' : null };
export interface Project {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'category' : ProjectCategory,
  'images' : Array<string>,
}
export type ProjectCategory = { 'commercial' : null } |
  { 'bedroom' : null } |
  { 'bathroom' : null } |
  { 'office' : null } |
  { 'kitchen' : null } |
  { 'livingRoom' : null };
export interface Service {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'description' : string,
  'priceRange' : [] | [string],
}
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
  'image' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, ProductCategory, string, number], bigint>,
  'addProject' : ActorMethod<
    [string, ProjectCategory, string, bigint, Array<string>],
    bigint
  >,
  'addService' : ActorMethod<
    [string, string, Array<string>, [] | [string]],
    bigint
  >,
  'addTeamMember' : ActorMethod<[string, string, string, string], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteTeamMember' : ActorMethod<[bigint], undefined>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], bigint>,
  'updateProduct' : ActorMethod<
    [bigint, string, ProductCategory, string, number],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, ProjectCategory, string, bigint, Array<string>],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, Array<string>, [] | [string]],
    undefined
  >,
  'updateTeamMember' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];