/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'textiles' : IDL.Null,
  'furniture' : IDL.Null,
  'lighting' : IDL.Null,
  'decor' : IDL.Null,
});
export const ProjectCategory = IDL.Variant({
  'commercial' : IDL.Null,
  'bedroom' : IDL.Null,
  'bathroom' : IDL.Null,
  'office' : IDL.Null,
  'kitchen' : IDL.Null,
  'livingRoom' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Float64,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : ProjectCategory,
  'images' : IDL.Vec(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'priceRange' : IDL.Opt(IDL.Text),
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'image' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, ProjectCategory, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ProjectCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'textiles' : IDL.Null,
    'furniture' : IDL.Null,
    'lighting' : IDL.Null,
    'decor' : IDL.Null,
  });
  const ProjectCategory = IDL.Variant({
    'commercial' : IDL.Null,
    'bedroom' : IDL.Null,
    'bathroom' : IDL.Null,
    'office' : IDL.Null,
    'kitchen' : IDL.Null,
    'livingRoom' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Float64,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : ProjectCategory,
    'images' : IDL.Vec(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'priceRange' : IDL.Opt(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'image' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, ProjectCategory, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ProjectCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };